inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 28

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'api_auth.gemspec'

Naming/FileName:
  Exclude:
    - 'lib/api-auth.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - 'gemfiles/*.gemfile'

Lint/DuplicateBranch:
  Enabled: false
