# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{api-auth}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mauricio Gomes"]
  s.date = %q{2011-01-30}
  s.description = %q{Full HMAC auth implementation for use in your gems and Rails apps.}
  s.email = %q{mgomes@geminisbs.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "lib/api-auth.rb",
    "spec/api-auth_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/geminisbs/api-auth}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.1}
  s.summary = %q{Simple HMAC authentication for your APIs}
  s.test_files = [
    "spec/api-auth_spec.rb",
    "spec/headers_spec.rb",
    "spec/helpers_spec.rb",
    "spec/railtie_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<amatch>, ["~> 0.2.5"])
      s.add_development_dependency(%q<curb>, ["~> 0.7.7"])
      s.add_development_dependency(%q<rest-client>, ["~> 1.6.0"])
      s.add_development_dependency(%q<actionpack>, ["~> 2.3.2"])
      s.add_development_dependency(%q<activeresource>, ["~> 2.3.2"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<amatch>, ["~> 0.2.5"])
      s.add_dependency(%q<curb>, ["~> 0.7.7"])
      s.add_dependency(%q<rest-client>, ["~> 1.6.0"])
      s.add_dependency(%q<actionpack>, ["~> 2.3.2"])
      s.add_dependency(%q<activeresource>, ["~> 2.3.2"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<amatch>, ["~> 0.2.5"])
    s.add_dependency(%q<curb>, ["~> 0.7.7"])
    s.add_dependency(%q<rest-client>, ["~> 1.6.0"])
    s.add_dependency(%q<actionpack>, ["~> 2.3.2"])
    s.add_dependency(%q<activeresource>, ["~> 2.3.2"])
  end
end

